IgnoreURLs:
  - .*localhost.*
  - https://expedia.com
  - https://www.expedia.com
  - https://github.com/linkerd/website/edit/master/linkerd.io/content/.*
  - https://ticketmaster.com
  - https://douban.com/
  - https://www.meetup.com/*
  - https://sched.co/*
  - https://marketplace.visualstudio.com/items*
  - https://www.xfinity.com/
  - https://monkey.org/*
DirectoryPath: public
