IgnoreURLs:
  - .*localhost.*
  - https://expedia.com
  - https://www.expedia.com
  - https://github.com/linkerd/website/edit/master/linkerd.io/content/.*
  - https://ticketmaster.com
  - https://douban.com/
  - https://www.douban.com/
  - https://www.meetup.com/*
  - https://sched.co/*
  - https://marketplace.visualstudio.com/items*
  - https://www.xfinity.com/
  - https://monkey.org/*
  - https://svn.apache.org/*
  - https://github.com/linkerd/linkerd2
  - https://github.com/linkerd/website/tree/master/linkerd.io/content
  - http://roc.cs.berkeley.edu/papers/dsconfig.pdf
  - https://discourse.linkerd.io
DirectoryPath: public
TestFilesConcurrently: true
DocumentConcurrencyLimit: 32
HTTPConcurrencyLimit: 16
ExternalTimeout: 15
