IgnoreURLs:
  - .*localhost.*
  - https://expedia.com
  - https://www.expedia.com
  - https://ticketmaster.com
  - https://douban.com/
  - https://www.douban.com/
  - https://www.meetup.com/*
  - https://sched.co/*
  - https://marketplace.visualstudio.com/items*
  - https://www.xfinity.com/
  - https://monkey.org/*
  - https://svn.apache.org/*
  - http://roc.cs.berkeley.edu/papers/dsconfig.pdf
  - https://discourse.linkerd.io
  - https://github.com/*
  - https://www.man7.org/*
DirectoryPath: public
TestFilesConcurrently: true
DocumentConcurrencyLimit: 16
HTTPConcurrencyLimit: 4
ExternalTimeout: 25
