apiVersion: apps/v1
kind: Deployment
metadata:
  name: podinfo
  namespace: test
spec:
  replicas: 1
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
---
apiVersion: v1
kind: Service
metadata:
  name: podinfo
  namespace: test
---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: podinfo
  namespace: test
