# Only relate content using keywords and tags
indices:
  - applyFilter: false
    cardinalityThreshold: 0
    name: keywords
    pattern: ""
    toLower: false
    type: basic
    weight: 100
  - applyFilter: false
    cardinalityThreshold: 0
    name: tags
    pattern: ""
    toLower: false
    type: basic
    weight: 80
threshold: 80
toLower: false
# `includeNewer: true`: All related content is shown, regardless of the date. Related content for older posts may change as new related content gets added.
# `includeNewer: false`: Related content is only shown if it's older than the current page
includeNewer: false
