apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  template:
    spec:
      containers:
      - name: external
        env:
        - name: SERVICE
          value: podinfo-west
