---
apiVersion: v1
kind: Service
metadata:
  name: webapp
spec:
  selector:
    app: webapp
  type: LoadBalancer
  ports:
  - name: service
    port: 7000
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: webapp
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: webapp
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/booksapp:v0.0.1
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: AUTHORS_SITE
          value: http://authors:7001
        - name: BOOKS_SITE
          value: http://books:7002
        args: ["prod:webapp"]
        readinessProbe:
          httpGet:
            path: /ping
            port: 7000
          initialDelaySeconds: 10
          failureThreshold: 12 # 2 minutes
        ports:
        - name: service
          containerPort: 7000
---
apiVersion: v1
kind: Service
metadata:
  name: authors
spec:
  selector:
    app: authors
  clusterIP: None
  ports:
  - name: service
    port: 7001
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: authors
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: authors
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/booksapp:v0.0.1
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: BOOKS_SITE
          value: http://books:7002
        - name: FAILURE_RATE
          value: "0.5"
        args: ["prod:authors"]
        readinessProbe:
          httpGet:
            path: /ping
            port: 7001
          initialDelaySeconds: 10
          failureThreshold: 12 # 2 minutes
        ports:
        - name: service
          containerPort: 7001
---
apiVersion: v1
kind: Service
metadata:
  name: books
spec:
  selector:
    app: books
  clusterIP: None
  ports:
  - name: service
    port: 7002
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: books
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: books
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: service
        image: buoyantio/booksapp:v0.0.1
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        - name: AUTHORS_SITE
          value: http://authors:7001
        args: ["prod:books"]
        readinessProbe:
          httpGet:
            path: /ping
            port: 7002
          initialDelaySeconds: 10
          failureThreshold: 12 # 2 minutes
        ports:
        - name: service
          containerPort: 7002
---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: traffic
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: traffic
    spec:
      dnsPolicy: ClusterFirst
      containers:
      - name: traffic
        image: buoyantio/booksapp-traffic:v0.0.1
        args:
        - "webapp:7000"
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  ports:
  - port: 3306
  selector:
    app: mysql
  clusterIP: None
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: password
        - name: MYSQL_DATABASE
          value: booksapp_production
        - name: MYSQL_USER
          value: booksapp
        - name: MYSQL_PASSWORD
          value: booksapp
        - name: MYSQL_INITDB_SKIP_TZINFO
          value: "1"
        ports:
        - containerPort: 3306
          name: mysql
---
apiVersion: batch/v1
kind: Job
metadata:
  name: mysql-init
spec:
  template:
    metadata:
      name: mysql-init
    spec:
      containers:
      - name: mysql-init
        image: buoyantio/booksapp:v0.0.1
        env:
        - name: DATABASE_URL
          value: mysql2://booksapp:booksapp@mysql:3306/booksapp_production
        command:
        - "/bin/sh"
        args:
        - "-c"
        - |
          set -e
          bundle exec rake db:ready
          bundle exec rake db:migrate
          bundle exec rake db:seed
      restartPolicy: OnFailure
