---
apiVersion: v1
kind: Namespace
metadata:
  name: multicluster-test
---
  apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: podinfo
    namespace: multicluster-test
  spec:
    minReadySeconds: 3
    revisionHistoryLimit: 5
    progressDeadlineSeconds: 60
    strategy:
      rollingUpdate:
        maxUnavailable: 0
      type: RollingUpdate
    selector:
      matchLabels:
        app: podinfo
    template:
      metadata:
        annotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "9797"
        labels:
          app: podinfo
      spec:
        containers:
        - name: podinfod
          image: stefanprodan/podinfo:4.0.1
          imagePullPolicy: IfNotPresent
          ports:
          - name: http
            containerPort: 9898
            protocol: TCP
          - name: http-metrics
            containerPort: 9797
            protocol: TCP
          - name: grpc
            containerPort: 9999
            protocol: TCP
          command:
          - ./podinfo
          - --port=9898
          - --port-metrics=9797
          - --grpc-port=9999
          - --grpc-service-name=podinfo
          - --level=info
          - --random-delay=false
          - --random-error=false
          env:
          - name: PODINFO_UI_COLOR
            value: "#34577c"
          livenessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:9898/healthz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          readinessProbe:
            exec:
              command:
              - podcli
              - check
              - http
              - localhost:9898/readyz
            initialDelaySeconds: 5
            timeoutSeconds: 5
          resources:
            limits:
              cpu: 2000m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 64Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-one
  namespace: multicluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-one
  template:
    metadata:
      labels:
        app: backend-one
    spec:
      containers:
      - name: backend-one
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=8888"
        - "--response-text=hello-remote-1"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: backend-one-svc
  namespace: multicluster-test
spec:
  selector:
    app: backend-one
  ports:
  - name: http
    port: 8888
    targetPort: 8888
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-two
  namespace: multicluster-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-two
  template:
    metadata:
      labels:
        app: backend-two
    spec:
      containers:
      - name: backend-two
        image: buoyantio/bb:v0.0.5
        args:
        - terminus
        - "--h1-server-port=8888"
        - "--response-text=hello-remote-2"
        ports:
        - containerPort: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: backend-two-svc
  namespace: multicluster-test
spec:
  selector:
    app: backend-two
  ports:
  - name: http
    port: 8888
    targetPort: 8888
