name: dx
on: push

jobs:
  runme:
    runs-on: ubuntu-latest
    environment: prod
    concurrency: ${{ vars.CLUSTER_NAME }}-cluster
    permissions:
      contents: 'read'
      id-token: 'write'
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - id: 'gcloud-auth'
        name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v1'
        with:
          workload_identity_provider: ${{ vars.GCLOUD_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.GCLOUD_SERVICE_ACCOUNT }}

      - id: 'get-credentials'
        uses: 'google-github-actions/get-gke-credentials@v1'
        with:
          cluster_name: ${{ vars.CLUSTER_NAME }}
          location: ${{ vars.CLUSTER_LOCATION }}
      
      - uses: azure/setup-kubectl@v3
        with:
          version: '1.27.4'

      - name: Check kubectl version
        run: |
          kubectl version

      - name: Install Linkerd
        run: |
          curl --proto '=https' --tlsv1.2 -sSfL https://run.linkerd.io/install | sh

      - name: Add Linkerd to PATH
        run: |
          echo "$PATH:/home/runner/.linkerd2/bin" >> $GITHUB_PATH

      - name: Validate Linkerd install
        run: linkerd version

      - name: 'Initialize Git submodules'
        run: |
          git submodule update --init
      
      - name: Run Bats Tests
        uses: stateful/runme-action@v1
        with:
          cwd: ${{ env.GITHUB_WORKSPACE }}
          serverAddress: ${{ vars.RUNME_ADDRESS }}
          run: npx bats ./tests/runme/getting-started.bats
        env:
          NO_COLOR: true
          FROM_CI: true
          RUNME_SERVER_ADDR: ${{ vars.RUNME_ADDRESS }}
      